language: c
install: git submodule init && git submodule update
script: make DEBUG=-O0 && make -j1 test
compiler: gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - gcc-8
            - libreadline6
      env:
         - MATRIX_EVAL="CC=gcc-8"

before_install:
    - eval "${MATRIX_EVAL}"
